apiVersion: v2
name: allure-testops-standalone
description: A Helm chart for Testops Deployment

type: application
version: 0.1.0

appVersion: "4.16.7"

kubeVersion: '>= 1.14.0-0'

home: https://qameta.io

maintainers:
  - name: Andrey Ryoo
    email: andrey.ryoo@qameta.io

dependencies:
  - name: rabbitmq
    version: 11.14.3
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: postgresql
    version: 12.4.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.10.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: minio
    version: 12.4.2
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
