---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gateway-secret
stringData:
  gateway.properties: |
    server.port={{ .Values.testops.service.gatewayPort }}
    spring.profiles.active=kubernetes
    spring.cloud.consul.enabled=false

    allure.secure={{ .Values.network.tls.enabled }}
    allure.jwt.secret={{ .Values.jwtSecret }}

    spring.session.store-type=REDIS

    spring.redis.host={{ template "allure-testops.redis.fullname" . }}
    spring.redis.port={{ .Values.redis.port }}
    spring.redis.database={{ .Values.redis.database }}
    spring.redis.password={{ .Values.redis.auth.password }}

    spring.cloud.discovery.client.simple.instances.allure-ee-gateway[0].instanceId=allure-ee-gateway-1
    spring.cloud.discovery.client.simple.instances.allure-ee-gateway[0].host={{ template "allure-testops-standalone.fullname" . }}
    spring.cloud.discovery.client.simple.instances.allure-ee-gateway[0].port={{ .Values.testops.service.gatewayPort }}

    spring.cloud.discovery.client.simple.instances.allure-ee-uaa[0].instanceId=allure-ee-uaa-1
    spring.cloud.discovery.client.simple.instances.allure-ee-uaa[0].host={{ template "allure-testops-standalone.fullname" . }}
    spring.cloud.discovery.client.simple.instances.allure-ee-uaa[0].port={{ .Values.testops.service.uaaPort }}

    spring.cloud.discovery.client.simple.instances.allure-ee-report[0].instanceId=allure-ee-report-1
    spring.cloud.discovery.client.simple.instances.allure-ee-report[0].host={{ template "allure-testops-standalone.fullname" . }}
    spring.cloud.discovery.client.simple.instances.allure-ee-report[0].port={{ .Values.testops.service.reportPort }}

    management.endpoints.web.exposure.include=health,info,prometheus,configprops
    management.endpoint.health.cache.time-to-live=15s

    spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://{{ template "allure-testops-standalone.fullname" . }}:{{ .Values.testops.service.reportPort }}/.well-known/jwks.json