apiVersion: v1
kind: Service
metadata:
  name: {{ template "allure-testops-standalone.fullname" . }}
  labels:
    app: {{ template "allure-testops-standalone.name" . }}
    version: v1
    chart: {{ template "allure-testops-standalone.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{ toYaml .Values.testops.service.annotations | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "allure-testops-standalone.name" . }}
    version: v1
  ports:
    - name: http-gtw
      protocol: TCP
      port: {{ .Values.testops.service.gatewayPort }}
      targetPort: {{ .Values.testops.service.gatewayPort }}
    - name: http-uaa
      protocol: TCP
      port: {{ .Values.testops.service.uaaPort }}
      targetPort: {{ .Values.testops.service.uaaPort }}
    - name: http-rep
      protocol: TCP
      port: {{ .Values.testops.service.reportPort }}
      targetPort: {{ .Values.testops.service.reportPort }}
