{{- if .Values.rbac.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "allure-testops-standalone.fullname" . }}-sa
  labels:
    app: {{ template "allure-testops-standalone.fullname" . }}
    chart: {{ template "allure-testops-standalone.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.aws.enabled }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.aws.arn }}"
{{- end }}

---
# create rbac role with permission for discovery
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "allure-testops-standalone.fullname" . }}-ns-reader
  labels:
    app: {{ template "allure-testops-standalone.fullname" . }}
    chart: {{ template "allure-testops-standalone.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
{{ toYaml .Values.rbac.rules | indent 2 }}

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "allure-testops-standalone.fullname" . }}-ns-reader
  labels:
    app: {{ template "allure-testops-standalone.fullname" . }}
    chart: {{ template "allure-testops-standalone.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ template "allure-testops-standalone.fullname" . }}-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "allure-testops-standalone.fullname" . }}-ns-reader

{{- end }}