---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: uaa-secret
stringData:
 uaa.properties: |

   server.port={{ .Values.testops.service.uaaPort }}
   spring.profiles.active=kubernetes
   spring.cloud.consul.enabled=false

   allure.endpoint={{ ternary "https" "http" .Values.network.tls.enabled }}://{{ .Values.host }}
   allure.jwt.secret={{ .Values.jwtSecret }}
   allure.crypto.password={{ .Values.cryptoPass }}
   allure.security.user.name={{ .Values.username }}
   allure.security.user.password={{ .Values.password }}
   allure.registration.autoapprove={{ .Values.testops.autoApprove }}
   allure.registration.enabled={{ .Values.testops.registrationEnabled }}
   allure.registration.default-role={{ .Values.testops.auth.defaultRole }}

   spring.datasource.url=jdbc:postgresql://{{ template "uaaDBHost" . }}:{{ template "uaaDBPort" . }}/{{ template "uaaDBName" . }}?sslmode={{ template "postgresSSL" . }}

{{- if .Values.postgresql.enabled }}
   spring.datasource.username={{ .Values.postgresql.auth.username }}
   spring.datasource.password={{ .Values.postgresql.auth.password }}
{{- else }}
   spring.datasource.username={{ .Values.postgresql.external.uaaUsername }}
   spring.datasource.password={{ .Values.postgresql.external.uaaPassword}}
{{- end }}

   spring.cloud.discovery.client.simple.instances.allure-ee-gateway[0].instanceId=allure-ee-gateway-1
   spring.cloud.discovery.client.simple.instances.allure-ee-gateway[0].host={{ template "allure-testops-standalone.fullname" . }}
   spring.cloud.discovery.client.simple.instances.allure-ee-gateway[0].port={{ .Values.testops.service.gatewayPort }}

   spring.cloud.discovery.client.simple.instances.allure-ee-uaa[0].instanceId=allure-ee-uaa-1
   spring.cloud.discovery.client.simple.instances.allure-ee-uaa[0].host={{ template "allure-testops-standalone.fullname" . }}
   spring.cloud.discovery.client.simple.instances.allure-ee-uaa[0].port={{ .Values.testops.service.uaaPort }}

   spring.cloud.discovery.client.simple.instances.allure-ee-report[0].instanceId=allure-ee-report-1
   spring.cloud.discovery.client.simple.instances.allure-ee-report[0].host={{ template "allure-testops-standalone.fullname" . }}
   spring.cloud.discovery.client.simple.instances.allure-ee-report[0].port={{ .Values.testops.service.reportPort }}

   management.endpoints.web.exposure.include=health,info,prometheus,configprops
   management.endpoint.health.cache.time-to-live=15s

   spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://{{ template "allure-testops-standalone.fullname" . }}:{{ .Values.testops.service.reportPort }}/.well-known/jwks.json