{{- if eq .Values.fs.type "CSI" }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "allure-testops.report.fullname" . }}
  labels:
    app: {{ template "allure-testops.report.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- with .Values.fs.csiStorage.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.fs.csiStorage.finalizers  }}
  finalizers:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.fs.csiStorage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.fs.csiStorage.size | quote }}
{{- if .Values.fs.csiStorage.existingVolumeName }}
  volumeName: {{ .Values.fs.csiStorage.existingVolumeName }}
{{- else }}
  storageClassName: {{ .Values.fs.csiStorage.storageClass }}
{{- end }}
{{- end }}
